### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by VTsuprov** [xtrinch/sx127x-node-driver#1]
https://registry.npmjs.org/sx127x-node-driver

{"error":"Not found"}

**Comment by xtrinch** [comment]
https://www.npmjs.com/package/sx127x-driver

I've updated the readme so the badge links to correct repository on NPM

**Comment by VTsuprov** [comment]
npm install sx127x-node-driver
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/sx127x-node-driver - Not
 found

**Comment by xtrinch** [comment]
Updated the readme to the correct name which is sx127x-driver

**Comment by xtrinch** [comment]
Oh and thanks!
