### ISSUE TITLE
setCodingRate logic incorrect

### ISSUE THREAD

**Issue by rgillan** [xtrinch/sx127x-node-driver#3]
Hello,
I raised this on node-sx127x a few years back and is the same issue here.  The logic to determine coding rate is incorrect, it should be:

if (cr <= (4/8)) { denominator = 8; } else if (cr <= (4/7)) { denominator = 7; } else if (cr <= (4/6)) { denominator = 6; } else { denominator = 5; }

**Comment by xtrinch** [comment]
You're right it's in wrong order, fixed in #174180d, thanks!
