### ISSUE TITLE
Support for RX IQ inversion

### ISSUE THREAD

**Issue by rgillan** [xtrinch/sx127x-node-driver#5]
For public LoRaWAN networks like TTN, it is standard practice to invert the receive LoRa I/Q (effectively stopping end devices communicating with each other directly).  It would be good if this could be added (potentially as an option but we have currently added it into open):

var REG_INVERT_IQ                = 0x33;

and

SX127x.prototype.open = async function()
{
...
  await this.sleep();
  let regInvertIQ = await this._readRegister(REG_INVERT_IQ);
  regInvertIQ |= 0x40;
  await this._writeRegister(REG_INVERT_IQ, regInvertIQ);

This has been tested and works well with a sx1276 device.

Cheers
Rob

**Comment by xtrinch** [comment]
Would you want this as a function in the library you can call, or as a side effect of the open, customized via options?

**Comment by rgillan** [comment]
A side effect of the open (by option) would be preferred.  It's not something that needs to be touched once the device is awake and ready for first transmission.  Interestingly it's not something detailed in the LoRaWAN specification and stumped us for a while (the IBM LMIC c implementation that most people use has the rx inversion set).

**Comment by xtrinch** [comment]
Published an update on NPM with the two fixes. Thanks!
