### ISSUE TITLE
Allowing DIO pin number 0

### ISSUE THREAD

**Issue by rgillan** [xtrinch/sx127x-node-driver#6]
There are a number of devices (e.g. FrendlyARM NanoPi NEO) where there is a valid GPIO number of 0.  We have found that passing 0 as an option to at least the resetPin it does not register, because:

this._resetPin = options.resetPin || 24;

will resolve to 24.  It may be better to use options.hasOwnProperty('resetPin') to determine whether present in the options passed to the constructor, rather than || with a default.

**Comment by xtrinch** [comment]
Yeah, sounds perfectly valid. Want to submit a PR or should I tackle it?

**Comment by rgillan** [comment]
So expect it's easier for you just to do.  Here's what we did to fix the issue:

function SX127x(options) {
  this._spiBus = options.spiBus || 0;
  this._spiDevice = options.spiDevice || 0;
  this._resetPin = (options.hasOwnProperty('resetPin')) ? options.resetPin : 24;
  this._dio0Pin = (options.hasOwnProperty('dio0Pin')) ? options.dio0Pin : 25;
  this._frequency = options.frequency || 915e6;
  this._spreadingFactor = options.spreadingFactor || 7;
  this._signalBandwidth = options.signalBandwidth || 125E3;
  this._codingRate = options.codingRate || (4 / 5);
  this._preambleLength = options.preambleLength || 8;
  this._syncWord = options.syncWord || 0x12;
  this._txPower = options.txPower || 17;
  this._crc = options.crc || false;
  this._implicitHeaderMode = false;
  this._debug = options.debug || false;
  this._packetIndex = 0;
  this._tempCompensationFactor = options.tempCompensationFactor || 0;
}
